# Load libraries
# Conditions: sgControl(PBS-Treated) as ScrmSCF, sgControl(SCF-Treated) as ScrpSCF, sgEGR1(PBS-Treated) as Sg2mSCF, and sgEGR1(SCF-Treated) as Sg2pSCF
import pandas as pd
import numpy as np

# BPM values for each condition has been generated using deeptools multiBigwigSummary. bigWig files were generated by bamCoverage tool after merging the BAM files.
df = pd.read_table("data/Kit_EGR1_Response_ATAC_Peaks_BPM_normalized.tsv")

#print("Loaded table with columns:", df.columns.tolist())
#print("Number of peaks:", len(df))

# Annotation with individual peak ids
df["peak_id"] = [f"peak{i}" for i in range(1, len(df) + 1)]
df = df[["chr", "start", "end", "peak_id", "ScrpSCF", "ScrmSCF", "Sg2pSCF", "Sg2mSCF"]]

# Compute log2 fold-changes of BPM values

df["log2FC_Scr"] = np.log2(df["ScrpSCF"] / df["ScrmSCF"])
df["log2FC_KD"]  = np.log2(df["Sg2pSCF"] / df["Sg2mSCF"])

# Setting fold-change threshold at 1.5 (log2-scale: 0.585)

up_thr   = 0.585
down_thr = -0.585

def call_state(x):
    if x >= up_thr:
        return "UP"
    elif x <= down_thr:
        return "DOWN"
    else:
        return "NEUTRAL"

df["state_Scr"] = df["log2FC_Scr"].apply(call_state)
df["state_KD"]  = df["log2FC_KD"].apply(call_state)

# Annotation of peak condition

df["grid"] = "Scr_" + df["state_Scr"] + "_KD_" + df["state_KD"]

print("\nGrid counts (3×3 states):")
print(df["grid"].value_counts().sort_index())


df["EGR1_sensitivity"] = "Kit_Neutral"

sens_act = ["Scr_UP_KD_NEUTRAL", "Scr_UP_KD_DOWN"]
df.loc[df["grid"].isin(sens_act), "EGR1_sensitivity"] = "EGR1_sensitive_activation"

sens_rep = ["Scr_DOWN_KD_NEUTRAL", "Scr_DOWN_KD_UP"]
df.loc[df["grid"].isin(sens_rep), "EGR1_sensitivity"] = "EGR1_sensitive_repression"

ins_act = ["Scr_UP_KD_UP"]
df.loc[df["grid"].isin(ins_act), "EGR1_sensitivity"] = "EGR1_insensitive_activation"

ins_rep = ["Scr_DOWN_KD_DOWN"]
df.loc[df["grid"].isin(ins_rep), "EGR1_sensitivity"] = "EGR1_insensitive_repression"

ins_base = ["Scr_NEUTRAL_KD_NEUTRAL"]
df.loc[df["grid"].isin(ins_base), "EGR1_sensitivity"] = "EGR1_insensitive_neutral"

# print("\nEGR1_sensitivity category counts:")
# print(df["EGR1_sensitivity"].value_counts())

# df.to_csv("EGR1_Sensitivity_Status_ATAC_peaks.tsv", sep="\t", index=False)


